version: '3'
services: 
    prometheus:
        image: prom/prometheus
        ports: 
            - 9090:9090
        volumes: 
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
        networks: 
            monitoring:
                aliases: 
                    - prometheus.localhost
    database:
        image: mariadb:10.5
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./database:/var/lib/mysql
            - ./scripts:/docker-entrypoint-initdb.d/
        ports: 
            - 3306
        networks: 
            monitoring:
                aliases: 
                    - database.localhost
    exporter:
        image: prom/mysqld-exporter
        environment: 
            DATA_SOURCE_NAME: "mysqld_exporter:passwordExporter@(database.localhost:3306)/"
        ports: 
            - 9104:9104
        networks: 
            monitoring:
                aliases: 
                    - exporter.localhost
networks: 
    monitoring: